### ISSUE TITLE
Use GitHub Action ?

### ISSUE THREAD

**Issue by vhiairrassary** [scallop/scallop#221]
Following recent [Travis CI announcement](https://travis-ci.community/t/open-source-at-travis-ci-an-update/10674), do you want me to add GitHub Actions to the repository? Unit test would run on every push, including PR.

**Comment by Rogach** [comment]
Yes, that would be a great idea!

**Comment by vhiairrassary** [comment]
Cool! I think I will need your help to enable it on the repository. You certainly have to add the first actions such as `.github/workflows/ci.yml` with:
```yml
name: Continuous Integration

on: push

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unit tests
        run: |
          echo 'Hello World'
```
Once it is done I will be able to create a PR with the complete action (tests, cache, etc.).
